# Values used for the deployed application.
replicaCount: 2

eksCluster: true

service:
  name: annotations-publisher

encryptedsecrets:
  publish.auth: "AgBGCyNdxl+414IocN123oIEBbxrry3GdXceO6+O0jUM/OT592KHozk47BniEnaelQ/fYk0F4HYfZeoAS/DJ/mJi7ZAEDrT1EneDbsgfSzUUHr5VN04JUa57rE7IAj05DpxW8Y4X96TPqZNm4Bx2fw1iLnAl3MzItUCItutSVqsCl18tiFdE78el8QFNPaGHYvwpYzNsC5q44r6x6R34MCprg80wPJPhsVOlhQY5+Mxi7ds+VLJtvaRv+xt8uc0ZrEpkpRKSm3HPd0eQw039tAdyJZpX7fdlY3ENoNZP1KXNP1P7pi6KLEns9j+RbsiFtyIHEdP0vWxRoO7qNrxl1ax73suR4jBTiZJJsMubEYvVKNDxgSEqUWuDEnNK8VZInS3jOM52hIjG2oQ9v7sXm9DD5fQFMAHCtVgvZrQ80ocN2Vz1gcQ089lI39MOt+kqL9FLpCvxzhWb0XcYb1vkdpsD6FMgGIDplKL4N0z8H/C8xE1Ts5xQLfVXQ1IIeZeXhZAUhajN+8MoBwn+OaSPU92dd62mRcWYTCuydFKlJg0sBefi8mtw0RVZrnL6WePtwtIObE16VeGg5go4hO3vwi1m55rvU35Jz97+UTU+fLDsHtsFHQszvwIDZAXEdFGZV+z9xf7aVZ0XGa8wvKOb3wPA2CX5619FCiwzLEtNvwRMSZW79yd2H7/pkkEVawyttB0l6jE/QRNk7wvF7cEGENIRz8ZV9/zCI+Uyxfa1nMNaZezS0M8="
