# Values used for the deployed application.
replicaCount: 2

eksCluster: true

service:
  name: annotations-publisher

encryptedsecrets:
  publish.auth: "AgAL3SvYp/R63bUtGkOQwTjnRafVZYRyjVqOBJAk74gPVyeSCOgZNnmLminxkZQ/Deh31s4EmBzj0jGJnBu9uarEwA4Se4Tw1bzsw+B/ZWj28K0clrgTPP49uTqdTVhSUJ9WaDxmWYHCirxYy2iQPMBseyViIBKR4jnNbUNzAFjFuIgWRWiYg3c5oTO2fF2O2GHtEm+HfSh5JOwmfWbWvJlraEarqpYQ0kY4YhxW/7XlFlMxB/I3XWwoqhsuqza1qABXiE3CUh56XHwlbvAqTVjN2G3YJHzRDtpw4R7bbE007OZu3GeVVQpytYb/xbDJu2ImqiTgs+9vIzaKGbrBpHrj7a3/XBRu6JecmJnJG8W64uX/iJwqwmr4pYt0jGw4Aw6qep+yYmAU4ct8D7sJjytau4nwlBbyd7s5ecb/A8zyoXrE+7eYCdzcybqC6fZ3kYFGSU7BWoeIqWavtxBAV/CAypiHISCC57ACBNyk3XqzpsPlUaQXgPgjuyXWXkLDrV9iCcCHL8AGuoZMAEWUHb2xMPQAJ9VyekXwRUEuVKMYijjaZJ7sfFY1PhFqVc3kTYF0CB3xb0xJuCyiwt6CPGTcl+XieLLDS4hSugZzOW2k+fiSznTceseOnF7nJu9ZTeGlUrzD75p0sF6EpdKIM1vDyd2CaEIg/m4TUAepPR2My/gvDStC8La2TR2qcRg1zEaqqcejMTap5TbX4q/s+OnPZv9ecsyztVWsqyBh4cmp5iTjyCI="
