# Values used for the deployed application.
replicaCount: 2

eksCluster: true

service:
  name: annotations-publisher

encryptedsecrets:
  publish.auth: "AgBL5Svjcm6RJ/B1MHWm8cgeitP/ghoaVwTi9xKiHHA/wBfEOxnPrU25n9m+3zH4SafptBO7c2O18w+ONVc2G5vfxfnc3QRPO0GEMXw5ke4SWjsgEkHr1kLv9A8k89AzDf7MzE3dkYQWaVf5AsprG20IssEAynxMBTC5fEXvs3sxRTvaACQ8rmu02V9KXX0maG/ZIGXTSY6hS+invLVAOe+mdMKaQKj/ksEEgn/fxAf9cLcfoimx9SB7NWqZvieUmeAh5PBTXf8B6H8Y52ATFGlMUxWkwzFeExlcDG2i13T5LptBTiTK1C/K2tCfchkEssRgvmXQlDdEUtTDCXFRbMsd8p/qCA6Gj4Zj/lVVgJOp/FANORUlCL3qhcUqGbRPRzvRHWS+VCFa9IsEqXH+7kjaPL9MatQUL83vjg9e3ghEMHuCGN1ocAfa9oRCq1A3v/JqpOJX4W3xfIkZMvb9bIbZYWw5LYvMDjvgpxMUJ5V4R03FFl8eay2tbpurG3SjH8W8RGTVkKDpLioIK+/I5OFPs1UQPaZmO1rys4YtRN49P05q5q9iOSVo3OXtBP4+F6GMgoYZhteKJ81bW2MToq8UqvHnbwtsR3FWAHCyfx7hMdj4hlR81mx1ZXwKlj6Ra1nSzCfR9CRufi4rc9lW/8Saet35RtxgIDUiZaGakmTFhnDxW20v5dCvxA0F+8IMXdOsNs/d4DET1N5RfkyXtADLRHY4hSBGFUWrfH8I+zKZIKAYIs8="
