service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  hasOpenAPI: "true"

replicaCount: 2

image:
  repository: coco/annotations-publisher
  pullPolicy: Always

env:
  annotationsPublishEndpoint: "http://cms-metadata-notifier:8080/notify"
  annotationsPublishGTGEndpoint: "http://cms-metadata-notifier:8080/__gtg"
  draftAnnotationsEndpoint: "http://draft-annotations-api:8080/draft-annotations/content/%v/annotations"
  draftAnnotationsGTGEndpoint: "http://draft-annotations-api:8080/__gtg"
  httpClientTimeout: "8s"
  jsonSchemasPath: "/schemas"
  jsonSchemaName: "annotations-pac.json;annotations-sv.json"
